site_name: Magic-Reports
copyright: "&copy; 2024 Lukas Forer"

theme:
  name: material
  features:
    - content.tooltips
    #- navigation.expand
    - navigation.footer
    - navigation.tabs
    #- navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.tabs.link
    - content.code.copy
  font:
    text: Segoe UI

  palette:
    primary: "blue grey"
    accent: blue

  icon:
    logo: material/rocket-launch
  favicon: images/favicon.svg

extra_css:
  - "style.css"

extra_javascript:
  - https://buttons.github.io/buttons.js

repo_url: https://github.com/lukfor/magic-reports

nav:
  - Home: index.md
  - Installation: installation.md
  - Documentation:
      - Getting Started: docs/getting-started.md
      - Building Reports: docs/report.md
      - Html Builder: docs/html-builder.md
      - Parameters: docs/parameters.md
      - Creating Components: docs/creating-components.md
      - Creating Templates: docs/creating-templates.md
  - Templates:
    - Home: templates/index.md
  - Components:
    - Home:  components/index.md
    - Bootstrap: components/bootstrap.md
    - DataTable: components/datatable.md
    - Plotly: components/plotly.md

  - Examples: examples.md
  - About: about.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
