#!/bin/bash
APP_HOME="$HOME/.magic-reports"
APP_JAR="magic-reports.jar"

set -e

FOLDER=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if test -f "${FOLDER}/${APP_JAR}"; then
  FILE_PATH_JAR=${FOLDER}/${APP_JAR}
else
  FILE_PATH_JAR=${APP_HOME}/${APP_JAR}
fi

export JAVA_PROGRAM_ARGS=`echo "$@"`

java -Xmx10G -jar "${FILE_PATH_JAR}" "$@"